<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $public->img;?>/apple-icon.png" />
	<link rel="icon" type="image/png" href="<?php echo $public->img;?>/favicon.png" />

	<title>What to Eat by Creative Leo</title>

	<!-- CSS Files -->
	<link href="<?php echo $public->css;?>/bootstrap.min.css" rel="stylesheet" />

	<!-- Fonts and Icons -->
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="<?php echo $public->css;?>/themify-icons.css" rel="stylesheet">
</head>

<body>
<div style="padding: 5px;">
	<table class="table table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th>餐厅名称</th>
				<th>描述</th>
				<th>地址</th>
				<th>时间</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th scope="row">1</th>
				<td><?php echo '餐厅:'.$choose['name'];?></td>
				<td><?php echo '描述:'.$choose['detail'];?></td>
				<td><?php echo '地址:'.$choose['address'];?></td>
				<td><?php echo '时间:'.date('Y-m-d', $choose['time']);?></td>
			</tr>
		</tbody>
	</table>
</div>

</body>

<!--   Core JS Files   -->
<script src="<?php echo $public->js;?>/jquery-2.2.4.min.js" type="text/javascript"></script>
<script src="<?php echo $public->js;?>/bootstrap.min.js" type="text/javascript"></script>

<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
<script src="<?php echo $public->js;?>/jquery.validate.min.js" type="text/javascript"></script>
</html>

