<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
	<meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="<?php echo $public->img;?>/apple-icon.png" />
	<link rel="icon" type="image/png" href="<?php echo $public->img;?>/favicon.png" />

	<title>What to Eat by Creative Leo</title>

	<!-- CSS Files -->
	<link href="<?php echo $public->css;?>/bootstrap.min.css" rel="stylesheet" />
	<link href="<?php echo $public->css;?>/paper-bootstrap-wizard.css" rel="stylesheet" />

	<!-- Fonts and Icons -->
	<link href="http://netdna.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.css" rel="stylesheet">
	<link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
	<link href="<?php echo $public->css;?>/themify-icons.css" rel="stylesheet">
</head>

<body>
<div class="image-container set-full-height" style="background-image: url('<?php echo $public->img;?>/paper-3.jpeg')">

	<!--   Big container   -->
	<div class="container">
		<div class="row">
			<div class="col-sm-8 col-sm-offset-2">

				<!--      Wizard container        -->
				<div class="wizard-container">
					<div class="card wizard-card" data-color="green" id="wizard">
						<form id="eat_info" action="" method="post">
							<!--        You can switch " data-color="green" "  with one of the next bright colors: "blue", "azure", "orange", "red"       -->

							<div class="wizard-header">
								<h3 class="wizard-title">List your Location</h3>
								<p class="category">This information will let us know more about your place.</p>
							</div>
							<div class="wizard-navigation">
								<div class="progress-with-circle">
									<div class="progress-bar" role="progressbar" aria-valuenow="1" aria-valuemin="1" aria-valuemax="4" style="width: 15%;"></div>
								</div>
								<ul>
									<li>
										<a href="#location" data-toggle="tab">
											<div class="icon-circle">
												<i class="ti-map"></i>
											</div>
											Location
										</a>
									</li>
									<li>
										<a href="#details" data-toggle="tab">
											<div class="icon-circle">
												<i class="ti-panel"></i>
											</div>
											Details
										</a>
									</li>
								</ul>
							</div>
							<div class="tab-content">
								<div class="tab-pane" id="location">
									<div class="row">
										<div class="col-sm-12">
											<h5 class="info-text"> Let's start with the basic details</h5>
										</div>
										<div class="col-sm-5 col-sm-offset-1">
											<div class="form-group">
												<label>Landmark*</label>
												<input type="text" class="form-control" name="landmark" id="landmark" placeholder="Where is your location?">
											</div>
										</div>
										<div class="col-sm-5">
											<div class="form-group">
												<label>Range</label>
												<select class="form-control">
													<option disabled="" selected="">- range -</option>
													<option value="1">1km</option>
													<option value="2">2km</option>
													<option value="3">5km</option>
												</select>
											</div>
										</div>
									</div>
								</div>
								<div class="tab-pane" id="details">
									<h5 class="info-text">Tell us more about details. </h5>
									<div class="row">
										<div class="col-sm-5 col-sm-offset-1">
											<div class="form-group">
												<label>How to Feel</label>
												<select class="form-control">
													<option disabled="" selected="">- type -</option>
													<option value="1">Normal</option>
													<option value="2">Happy</option>
													<option value="3">Sad</option>
												</select>
											</div>
										</div>
										<div class="col-sm-5">
											<div class="form-group">
												<label>Especially want to eat</label>
												<input type="text" class="form-control" id="eat" placeholder="Especially want to eat?"/>
											</div>
										</div>
									</div>
								</div>
							</div>
							<div class="wizard-footer">
								<div class="pull-right">
									<input type='button' class='btn btn-next btn-fill btn-success btn-wd' name='next' value='Next' />
									<input type='button' class='btn btn-finish btn-fill btn-success btn-wd' name='finish' value='Finish'/>
								</div>

								<div class="pull-left">
									<input type='button' class='btn btn-previous btn-default btn-wd' name='previous' value='Previous' />
								</div>
								<div class="clearfix"></div>
							</div>
						</form>
					</div>
				</div> <!-- wizard container -->
			</div>
		</div> <!-- row -->
	</div> <!--  big container -->

	<div class="footer">
		<div class="container text-center">
			made with <i class="fa fa-heart heart"></i> by <a href="#">Creative Leo.</a>
		</div>
	</div>
</div>

</body>

<!--   Core JS Files   -->
<script src="<?php echo $public->js;?>/jquery-2.2.4.min.js" type="text/javascript"></script>
<script src="<?php echo $public->js;?>/bootstrap.min.js" type="text/javascript"></script>
<script src="<?php echo $public->js;?>/jquery.bootstrap.wizard.js" type="text/javascript"></script>
<script src="<?php echo $public->js;?>/jquery.form.min.js" type="text/javascript"></script>

<!--  Plugin for the Wizard -->
<script src="<?php echo $public->js;?>/paper-bootstrap-wizard.js" type="text/javascript"></script>

<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
<script src="<?php echo $public->js;?>/jquery.validate.min.js" type="text/javascript"></script>

<script type="text/javascript">
	$(document).ready(function (){
        $('#eat_info').ajaxForm(function() {
            alert("Thank you for your comment!");
        });
	});



</script>

</html>

